version: "3"


volumes:
  data:

services:
  db:
    container_name: battleship-db
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data